import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../core/network/api_client.dart';
import '../core/network/token_storage.dart';
import '../features/auth/data/auth_repository.dart';
import '../features/auth/state/auth_controller.dart';
import '../features/auth/state/auth_state.dart';
import '../app/theme_provider.dart';
final apiClientProvider=Provider<ApiClient>((ref)=>ApiClient());
final tokenStorageProvider=Provider<TokenStorage>((ref)=>const TokenStorage());
final authRepositoryProvider=Provider<AuthRepository>((ref)=>AuthRepository(client:ref.watch(apiClientProvider),tokenStorage:ref.watch(tokenStorageProvider)));
final authControllerProvider=StateNotifierProvider<AuthController,AuthState>((ref){final c=AuthController(ref.watch(authRepositoryProvider));ref.watch(apiClientProvider).onUnauthenticated=c.sessionExpired;return c;});
