import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../core/network/api_exception.dart';
import '../auth/state/auth_providers.dart';

class NotificationItem { const NotificationItem(this.json); final Map<String,dynamic> json; String get type=>json['type']?.toString()??''; String get title=>json['title']?.toString()??type; String get body=>json['body']?.toString()??''; bool get read=>json['is_read']==true; }

class NotificationsScreen extends ConsumerStatefulWidget { const NotificationsScreen({super.key}); @override ConsumerState<NotificationsScreen> createState()=>_NotificationsScreenState(); }
class _NotificationsScreenState extends ConsumerState<NotificationsScreen> { bool loading=true; bool reading=false; List<NotificationItem> items=[]; String? error; @override void initState(){super.initState();_load();} Future<void> _load()async{try{final d=(await ref.read(apiClientProvider).get('/notifications')).dataMap;final list=d['items'] is List?(d['items'] as List):const [];if(mounted)setState((){items=list.whereType<Map>().map((e)=>NotificationItem(e.cast<String,dynamic>())).toList();loading=false;});}on ApiException catch(e){if(mounted)setState((){error=e.message;loading=false;});}} Future<void> _readAll()async{setState(()=>reading=true);try{await ref.read(apiClientProvider).post('/notifications/read-all');await _load();}finally{if(mounted)setState(()=>reading=false);}} @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Bildirishnomalar'),actions:[TextButton(onPressed:reading||items.isEmpty?null:_readAll,child:const Text('Barchasini o‘qish'))]),body:loading?const Center(child:CircularProgressIndicator()):error!=null?Center(child:Text(error!)):items.isEmpty?const Center(child:Text('Bildirishnomalar yo‘q')):RefreshIndicator(onRefresh:_load,child:ListView.separated(padding:const EdgeInsets.all(16),itemCount:items.length,separatorBuilder:(_,__)=>const SizedBox(height:8),itemBuilder:(_,i){final n=items[i];return Card(color:n.read?null:Theme.of(context).colorScheme.primaryContainer,child:ListTile(leading:Icon(n.read?Icons.notifications_none:Icons.notifications_active),title:Text(n.title,style:TextStyle(fontWeight:n.read?FontWeight.normal:FontWeight.bold)),subtitle:Text(n.body.isEmpty?_label(n):n.body));})));} String _label(NotificationItem n)=>switch(n.type){'debt_overdue'=>'Muddati o‘tgan qarz mavjud','low_stock'=>'Mahsulot qoldig‘i kamaygan','out_of_stock'=>'Mahsulot tugagan','subscription_expiring'=>'Tarif muddati tugamoqda',_=>'Yangi bildirishnoma'}; }
