import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../core/l10n/app_strings.dart';
import '../../core/widgets/widgets.dart';
import '../auth/state/auth_providers.dart';
import '../notifications/notifications_screen.dart';
import 'state/home_providers.dart';
import '../debts/debt_form_screen.dart';
import '../debts/debts_screen.dart';
import '../expenses/expenses_screen.dart';
import '../inventory/inventory_screen.dart';
import '../sales/sale_form_screen.dart';

class HomeScreen extends ConsumerStatefulWidget { const HomeScreen({super.key}); @override ConsumerState<HomeScreen> createState()=>_HomeScreenState(); }
class _HomeScreenState extends ConsumerState<HomeScreen> { @override void initState(){super.initState();Future.microtask(()=>ref.read(homeControllerProvider.notifier).load());} Future<void> _reload()=>ref.read(homeControllerProvider.notifier).load(); Future<void> _push(Widget s)async{await Navigator.of(context).push(MaterialPageRoute(builder:(_)=>s));if(mounted)await _reload();} @override Widget build(BuildContext context){final s=context.s;final state=ref.watch(homeControllerProvider);final name=ref.watch(authControllerProvider).user?.name??'';if(state.isLoading&&!state.hasData)return const Scaffold(body:Center(child:CircularProgressIndicator()));final sales=state.sales?.netTotal??0;final profit=state.sales?.profit??0;final debt=state.debts?.givenToday??0;final returned=state.debts?.returnedToday??0;final overdue=state.debts?.overdueCount??0;final low=state.products?.attentionCount??0;return Scaffold(body:SafeArea(child:RefreshIndicator(onRefresh:_reload,child:ListView(children:[_Header(userName:name),const SizedBox(height:16),Text('Bugungi savdo: $sales'),const SizedBox(height:16),_QuickActions(onOpen:_push),if(overdue>0)Text(s.overdueDebts(overdue)),if(low>0)Text(s.lowStock(low)),Text('Foyda: $profit | Qaytgan qarz: $returned'),])));}}
class _Header extends ConsumerWidget{const _Header({required this.userName});final String userName;@override Widget build(BuildContext context,WidgetRef ref){return Padding(padding:const EdgeInsets.fromLTRB(16,16,8,0),child:Row(children:[Expanded(child:Text(userName)),_NotificationButton()]));}}
class _NotificationButton extends ConsumerStatefulWidget{const _NotificationButton();@override ConsumerState<_NotificationButton> createState()=>_NotificationButtonState();}
class _NotificationButtonState extends ConsumerState<_NotificationButton>{int count=0;@override void initState(){super.initState();_load();}Future<void> _load()async{try{final d=(await ref.read(apiClientProvider).get('/notifications')).dataMap;if(mounted)setState(()=>count=(d['unread_count'] as num?)?.toInt()??0);}catch(_){}}@override Widget build(BuildContext context)=>Stack(children:[IconButton(onPressed:()=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>const NotificationsScreen())).then((_)=>_load()),icon:const Icon(Icons.notifications_none_rounded,size:28)),if(count>0)Positioned(right:4,top:2,child:Container(padding:const EdgeInsets.symmetric(horizontal:5,vertical:2),decoration:BoxDecoration(color:Colors.red,borderRadius:BorderRadius.circular(10)),child:Text(count>99?'99+':'$count',style:const TextStyle(color:Colors.white,fontSize:10,fontWeight:FontWeight.bold))))]);}
class _QuickActions extends StatelessWidget{const _QuickActions({required this.onOpen});final Future<void> Function(Widget) onOpen;@override Widget build(BuildContext context)=>Row(children:[Expanded(child:QuickActionButton(label:'Savdo',icon:Icons.shopping_basket,onTap:()=>onOpen(const SaleFormScreen()))),Expanded(child:QuickActionButton(label:'Qarz',icon:Icons.account_balance_wallet,onTap:()=>onOpen(const DebtFormScreen()))),Expanded(child:QuickActionButton(label:'To‘lov',icon:Icons.payments,onTap:()=>onOpen(const DebtsScreen()))),Expanded(child:QuickActionButton(label:'Kirim',icon:Icons.inventory,onTap:()=>onOpen(const InventoryScreen())))]);}
